# Generated by Django 4.1.3 on 2023-08-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatname', models.CharField(max_length=255)),
                ('chatphone', models.IntegerField(null=True)),
                ('chatemail', models.EmailField(max_length=254)),
                ('chatstatus', models.TextField(blank=True, null=True)),
                ('chatremark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cmail', models.EmailField(max_length=200)),
                ('cphone', models.CharField(max_length=100)),
                ('cenquiry', models.CharField(max_length=100)),
                ('cmessage', models.TextField()),
                ('cstatus', models.TextField(blank=True, null=True)),
                ('cremark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='enrolldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('ephone', models.CharField(max_length=100)),
                ('ecourse', models.CharField(max_length=100)),
                ('estatus', models.TextField(blank=True, null=True)),
                ('eremark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='featuredEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('presented_by', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='phonedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('pstatus', models.TextField(blank=True, null=True)),
                ('premark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subscribe_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('semail', models.EmailField(max_length=254)),
                ('sstatus', models.TextField(blank=True, null=True)),
                ('sremark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='upcoming_popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='upcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('presented_by', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
