# Generated by Django 4.1.3 on 2023-08-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0002_chatdata_created_at_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdata',
            name='lead_in_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='lead_in_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrolldata',
            name='lead_in_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='featuredevent',
            name='lead_in_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phonedata',
            name='lead_in_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscribe_data',
            name='lead_in_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upcoming_popup',
            name='lead_in_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='lead_in_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
