# Generated by Django 4.1.3 on 2023-08-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0003_chatdata_lead_in_source_contactus_lead_in_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatdata',
            name='lead_in_source',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='lead_in_source',
        ),
        migrations.RemoveField(
            model_name='enrolldata',
            name='lead_in_source',
        ),
        migrations.RemoveField(
            model_name='featuredevent',
            name='lead_in_source',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='lead_in_source',
        ),
        migrations.RemoveField(
            model_name='subscribe_data',
            name='lead_in_source',
        ),
        migrations.RemoveField(
            model_name='upcoming_popup',
            name='lead_in_source',
        ),
        migrations.RemoveField(
            model_name='upcomingevent',
            name='lead_in_source',
        ),
    ]
