# Generated by Django 4.1.3 on 2023-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_remove_chatdata_lead_in_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_in_source', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
