# Generated by Django 4.1.3 on 2023-08-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0005_leadinsource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadInSource',
        ),
        migrations.AddField(
            model_name='contactus',
            name='lead_assigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='lead_in_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='lead_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
