# Generated by Django 4.1.3 on 2023-08-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0006_delete_leadinsource_contactus_lead_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='lead_in_source',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'instagram')], max_length=100, null=True),
        ),
    ]
