# Generated by Django 4.1.3 on 2023-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0009_contactus_cell1_contactus_cell2_contactus_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
