# Generated by Django 4.1.3 on 2023-08-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0013_phonedata_cell1_phonedata_cell2_phonedata_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonedata',
            name='cell1',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='cell2',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='lead_assigned',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='lead_in_source',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='lead_status',
        ),
        migrations.RemoveField(
            model_name='phonedata',
            name='notes',
        ),
    ]
