# Generated by Django 4.1.3 on 2023-08-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0016_enrolldata_cell1_enrolldata_cell2_enrolldata_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedata',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
