# Generated by Django 4.1.3 on 2023-08-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0017_phonedata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedata',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
